server:
  port: 8081
  servlet:
    context-path: /api-contact

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  docker:
    compose:
      lifecycle-management: start_and_stop


application-version: V 1.0

application-description: |
  The contact API allows:
  * Contacts display
  * Contact creation
  * Contact update
  * Deletion of contact

jwt:
  private:
    key: T9A7mseDfw45U32UC2tS23Vz4e9B3tiR7xh2ZcujQATVbaz8FS39hQ545J3dx7TQ

url:
  frontend: http://localhost:4200